spring.application.name=SpringJDBC


spring.datasource.url=jdbc:postgresql://localhost:5432/demo
spring.datasource.username=postgres
spring.datasource.password=achyutp10

spring.datasource.driver-class-name=org.postgresql.Driver

#spring.sql.init.mode=always